# Плагин запрещает разливать лаву/воду начиная с высоты
# однако воду с льда не запретит :(

height: 200 #Высота с которой запрещено наливать (если 200 то с 200 по 256)

disable-lava: true #Если true, то запретит лаву, если false - разрешит
disable-water: true #Если true, то запретит воду, если false - разрешит
disable-dispenser: true

message: "&c Запрещаю тебе разливать это с такой высоты"
type: message #message - сообщение в чат, actionbar - в акшионбар, subtitle - в субтитл
sound: ENTITY_VILLAGER_NO #звук

# Для релоада плагина используй /antiupperlava
# Право на релоад: antiupperlava.reload
# Можешь убрать надписи после хештегов # для экономии места